name: 'Test_B'

on:
  workflow_run:
    workflows: ["Test_A"]   # MUST match the "name" field of first workflow
    types:
      - completed

jobs:
  run-after-a:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Running after Test_A completes"